all: one two three four five six

one: fifo_1.c
	gcc fifo_1.c -o a

two: fifo_2.c
	gcc fifo_2.c -o b  
      
three: socket_1.c
	gcc socket_1.c -o c

four: socket_2.c
	gcc socket_2.c -o d

five: shmem_1.c
	gcc shmem_1.c -o e

six: shmem_2.c
	gcc shmem_2.c -o f
